import { pitDeps } from './pitDeps';
import { persistComputations, persistOne, type PersistedBatch } from '@/application/metrics/persistComputations';
import type { PitDeps } from '@/application/metrics/deps';
import type { BasisOutcome } from '@/application/metrics/pitOutcome';
import type { ComputationSlot, MetricComputation } from '@/domain/metrics/computation';
import type { MetricValueWriteOutcome } from '@/domain/metrics/coordinate';
import { computeBuybackYield } from '@/application/metrics/dividend/buybackYield/computeBuybackYield';
import { computeChowderNumber } from '@/application/metrics/dividend/chowderNumber/computeChowderNumber';
import { computeConsecutiveDividendYears } from '@/application/metrics/dividend/consecutiveDividendYears/computeConsecutiveDividendYears';
import { computeDividendCoverageRatio } from '@/application/metrics/dividend/dividendCoverageRatio/computeDividendCoverageRatio';
import { computeDividendDistributionCount } from '@/application/metrics/dividend/dividendDistributionCount/computeDividendDistributionCount';
import { computeDividendGrowthRateFamily } from '@/application/metrics/dividend/dividendGrowthRate/computeDividendGrowthRateFamily';
import { computeDividendPayoutRatio } from '@/application/metrics/dividend/dividendPayoutRatio/computeDividendPayoutRatio';
import { computeDividendPerShare } from '@/application/metrics/dividend/dividendPerShare/computeDividendPerShare';
import { computeShareCountChangeRate } from '@/application/metrics/dividend/shareCountChangeRate/computeShareCountChangeRate';
import { computeShareholderYield } from '@/application/metrics/dividend/shareholderYield/computeShareholderYield';
import { computeCapexToRevenue } from '@/application/metrics/efficiency/capexToRevenue/computeCapexToRevenue';
import { computeOperatingExpenseRatio } from '@/application/metrics/efficiency/operatingExpenseRatio/computeOperatingExpenseRatio';
import { computeTurnoverRatioFamily } from '@/application/metrics/efficiency/turnoverRatio/computeTurnoverRatioFamily';
import { computeAssetGrowth } from '@/application/metrics/growth/assetGrowth/computeAssetGrowth';
import { computeBvpsGrowthRate } from '@/application/metrics/growth/bvpsGrowthRate/computeBvpsGrowthRate';
import { computeEpsCagrFamily } from '@/application/metrics/growth/epsCagr/computeEpsCagrFamily';
import { computeEpsGrowthRate } from '@/application/metrics/growth/epsGrowthRate/computeEpsGrowthRate';
import { computeEquityGrowthRate } from '@/application/metrics/growth/equityGrowthRate/computeEquityGrowthRate';
import { computeNetIncomeGrowthRate } from '@/application/metrics/growth/netIncomeGrowthRate/computeNetIncomeGrowthRate';
import { computeOperatingIncomeGrowthRate } from '@/application/metrics/growth/operatingIncomeGrowthRate/computeOperatingIncomeGrowthRate';
import { computePriceToResearchRatio } from '@/application/metrics/growth/priceToResearchRatio/computePriceToResearchRatio';
import { computeRdIntensity } from '@/application/metrics/growth/rdIntensity/computeRdIntensity';
import { computeRevenueCagrFamily } from '@/application/metrics/growth/revenueCagr/computeRevenueCagrFamily';
import { computeRevenueGrowthRate } from '@/application/metrics/growth/revenueGrowthRate/computeRevenueGrowthRate';
import { computeRuleOf40 } from '@/application/metrics/growth/ruleOf40/computeRuleOf40';
import { computeSgr } from '@/application/metrics/growth/sgr/computeSgr';
import { computeSue } from '@/application/metrics/growth/sue/computeSue';
import { computeBankIncomeWaterfall } from '@/application/metrics/profitability/bankIncomeWaterfall/computeBankIncomeWaterfall';
import { computeCroci } from '@/application/metrics/profitability/croci/computeCroci';
import { computeEps } from '@/application/metrics/profitability/eps/computeEps';
import { computeFamaFrenchOperatingProfitability } from '@/application/metrics/profitability/famaFrenchOperatingProfitability/computeFamaFrenchOperatingProfitability';
import { computeGreenblattRoc } from '@/application/metrics/profitability/greenblattRoc/computeGreenblattRoc';
import { computeIncomeStatementPerShare } from '@/application/metrics/profitability/incomeStatementPerShare/computeIncomeStatementPerShare';
import { computeMarginsFamily } from '@/application/metrics/profitability/margins/computeMarginsFamily';
import { computeNissimPenmanRnoa } from '@/application/metrics/profitability/nissimPenmanRnoa/computeNissimPenmanRnoa';
import { computeNonOperatingIncomeRatio } from '@/application/metrics/profitability/nonOperatingIncomeRatio/computeNonOperatingIncomeRatio';
import { computeNovyMarxGpToAssets } from '@/application/metrics/profitability/novyMarxGpToAssets/computeNovyMarxGpToAssets';
import { computeOneDollarTest } from '@/application/metrics/profitability/oneDollarTest/computeOneDollarTest';
import { computePretaxIncomePerShare } from '@/application/metrics/profitability/pretaxIncomePerShare/computePretaxIncomePerShare';
import { computeRevenuePerShare } from '@/application/metrics/profitability/revenuePerShare/computeRevenuePerShare';
import { computeRoa } from '@/application/metrics/profitability/roa/computeRoa';
import { computeRoce } from '@/application/metrics/profitability/roce/computeRoce';
import { computeRoe } from '@/application/metrics/profitability/roe/computeRoe';
import { computeRoic } from '@/application/metrics/profitability/roic/computeRoic';
import { computeAbnormalCapexRatio } from '@/application/metrics/quality/abnormalCapexRatio/computeAbnormalCapexRatio';
import { computeAccrualsRatio } from '@/application/metrics/quality/accrualsRatio/computeAccrualsRatio';
import { computeBeneishAqi } from '@/application/metrics/quality/beneishAqi/computeBeneishAqi';
import { computeBeneishDsri } from '@/application/metrics/quality/beneishDsri/computeBeneishDsri';
import { computeBeneishMScore } from '@/application/metrics/quality/beneishMScore/computeBeneishMScore';
import { computeCashFlowPerShare } from '@/application/metrics/quality/cashFlowPerShare/computeCashFlowPerShare';
import { computeConsecutiveProfitYears } from '@/application/metrics/quality/consecutiveProfitYears/computeConsecutiveProfitYears';
import { computeFcfMargin } from '@/application/metrics/quality/fcfMargin/computeFcfMargin';
import { computeOcfToNetIncome } from '@/application/metrics/quality/ocfToNetIncome/computeOcfToNetIncome';
import { computeOwnerEarnings } from '@/application/metrics/quality/ownerEarnings/computeOwnerEarnings';
import { computePiotroskiFScore } from '@/application/metrics/quality/piotroskiFScore/computePiotroskiFScore';
import { computeAltmanZDoublePrimeScore } from '@/application/metrics/resilience/altmanZDoublePrimeScore/computeAltmanZDoublePrimeScore';
import { computeAltmanZScore } from '@/application/metrics/resilience/altmanZScore/computeAltmanZScore';
import { computeBankAssetQualityFamily } from '@/application/metrics/resilience/bankAssetQuality/computeBankAssetQualityFamily';
import { computeBankCapitalAdequacyFamily } from '@/application/metrics/resilience/bankCapitalAdequacy/computeBankCapitalAdequacyFamily';
import { computeCashToAssetsRatio } from '@/application/metrics/resilience/cashToAssetsRatio/computeCashToAssetsRatio';
import { computeDebtRatio } from '@/application/metrics/resilience/debtRatio/computeDebtRatio';
import { computeDeRatio } from '@/application/metrics/resilience/deRatio/computeDeRatio';
import { computeEquityRatio } from '@/application/metrics/resilience/equityRatio/computeEquityRatio';
import { computeInterestCoverage } from '@/application/metrics/resilience/interestCoverage/computeInterestCoverage';
import { computeLeverageDegreeFamily } from '@/application/metrics/resilience/leverageDegreeFamily/computeLeverageDegreeFamily';
import { computeLiquidityRatio } from '@/application/metrics/resilience/liquidityRatio/computeLiquidityRatio';
import { computeLongTermDebtToNetCurrentAssets } from '@/application/metrics/resilience/longTermDebtToNetCurrentAssets/computeLongTermDebtToNetCurrentAssets';
import { computeNetDebtToEbitda } from '@/application/metrics/resilience/netDebtToEbitda/computeNetDebtToEbitda';
import { computeNetWorkingCapitalToAssets } from '@/application/metrics/resilience/netWorkingCapitalToAssets/computeNetWorkingCapitalToAssets';
import { computeOhlsonOScore } from '@/application/metrics/resilience/ohlsonOScore/computeOhlsonOScore';
import { computeTotalDebtToCapital } from '@/application/metrics/resilience/totalDebtToCapital/computeTotalDebtToCapital';
import { computeZmijewskiScore } from '@/application/metrics/resilience/zmijewskiScore/computeZmijewskiScore';
import { computeCashFlowValuationFamily } from '@/application/metrics/shared/cashFlowValuationFamily/computeCashFlowValuationFamily';
import { computeDupontFamily } from '@/application/metrics/shared/dupont/computeDupontFamily';
import { computeMarketRatios } from '@/application/metrics/shared/marketRatios/computeMarketRatios';
import { computeBeta } from '@/application/metrics/valuation/beta/computeBeta';
import { computeBvps } from '@/application/metrics/valuation/bvps/computeBvps';
import { computeEarningsYield } from '@/application/metrics/valuation/earningsYield/computeEarningsYield';
import { computeEvEbitda } from '@/application/metrics/valuation/evEbitda/computeEvEbitda';
import { computeEvToEbit } from '@/application/metrics/valuation/evToEbit/computeEvToEbit';
import { computeEvToFcf } from '@/application/metrics/valuation/evToFcf/computeEvToFcf';
import { computeFcfYield } from '@/application/metrics/valuation/fcfYield/computeFcfYield';
import { computeGrahamNumber } from '@/application/metrics/valuation/grahamNumber/computeGrahamNumber';
import { computeGreenblattEarningsYield } from '@/application/metrics/valuation/greenblattEarningsYield/computeGreenblattEarningsYield';
import { computeLiveGrahamNumber } from '@/application/metrics/valuation/liveGrahamNumber/computeLiveGrahamNumber';
import { computeLiveMarketCap } from '@/application/metrics/valuation/liveMarketCap/computeLiveMarketCap';
import { computeLivePegRatio } from '@/application/metrics/valuation/livePegRatio/computeLivePegRatio';
import { computeMarketCap } from '@/application/metrics/valuation/marketCap/computeMarketCap';
import { computeNcav } from '@/application/metrics/valuation/ncav/computeNcav';
import { computePbRatio } from '@/application/metrics/valuation/pbRatio/computePbRatio';
import { computePegRatio } from '@/application/metrics/valuation/pegRatio/computePegRatio';
import { computePeRatio } from '@/application/metrics/valuation/peRatio/computePeRatio';
import { computePFcf } from '@/application/metrics/valuation/pFcf/computePFcf';
import { computePsr } from '@/application/metrics/valuation/psr/computePsr';
import { computeStockPrice } from '@/application/metrics/valuation/stockPrice/computeStockPrice';
import { computeTobinsQ } from '@/application/metrics/valuation/tobinsQ/computeTobinsQ';

// 指標核心對 scripts/ 跟整合測試的出口：每支 computeXxx（純計算、deps 注入）綁上真實的 pitDeps 並接
// persistComputations 寫入，回傳攤平後的 outcome（{ symbol, rocYear, season, q, ttm, ... }）——跟重構前
// computeAndWriteXxxPit 的回傳形狀一樣，所以名稱也沿用。2026-09-17 Phase 3 收尾由
// scripts/codemods/generatePitMetricsBootstrap.ts 從 96 支 shim 產生一次，之後新增指標直接在這裡加一行。

type Batch = { slots: Record<string, ComputationSlot> };

export const runPit =
  <Q, B extends Batch>(compute: (query: Q, deps: PitDeps) => Promise<B>) =>
  async (query: Q): Promise<PersistedBatch<B>> =>
    persistComputations(await compute(query, pitDeps), pitDeps);

// epsCagr/revenueCagr/dividendGrowthRate 三個「一個回溯窗口一個 metric_code」的 family，舊 outcome 把各窗口的
// 結果巢狀在 `results` 底下（verifyMetricEquivalencePit 的 key 是 "results.epsCagr3y"）——攤平後再包回去。
export const runPitNested =
  <Q, B extends Batch, N extends string>(compute: (query: Q, deps: PitDeps) => Promise<B>, nestUnder: N) =>
  async (query: Q): Promise<Omit<B, 'slots'> & Record<N, Record<keyof B['slots'], BasisOutcome>>> => {
    const batch = await compute(query, pitDeps);
    const persisted = (await persistComputations(batch, pitDeps)) as Record<string, unknown>;
    const { slots, ...context } = batch;
    const nested = Object.fromEntries(Object.keys(slots).map((key) => [key, persisted[key]]));
    return { ...context, [nestUnder]: nested } as Omit<B, 'slots'> & Record<N, Record<keyof B['slots'], BasisOutcome>>;
  };

// 直接寫一筆（scripts/backfillMagicFormulaRankPit.ts 這種算完不是走 computeXxx 的呼叫端用）。
export const persistMetricValue = (input: MetricComputation): Promise<MetricValueWriteOutcome> => persistOne(input, pitDeps);

export const computeAndWriteBuybackYieldPit = runPit(computeBuybackYield);
export const computeAndWriteChowderNumberPit = runPit(computeChowderNumber);
export const computeAndWriteConsecutiveDividendYearsPit = runPit(computeConsecutiveDividendYears);
export const computeAndWriteDividendCoverageRatioPit = runPit(computeDividendCoverageRatio);
export const computeAndWriteDividendDistributionCountPit = runPit(computeDividendDistributionCount);
export const computeAndWriteDividendGrowthRateFamilyPit = runPitNested(computeDividendGrowthRateFamily, 'results');
export const computeAndWriteDividendPayoutRatioPit = runPit(computeDividendPayoutRatio);
export const computeAndWriteDividendPerSharePit = runPit(computeDividendPerShare);
export const computeAndWriteShareCountChangeRatePit = runPit(computeShareCountChangeRate);
export const computeAndWriteShareholderYieldPit = runPit(computeShareholderYield);
export const computeAndWriteCapexToRevenuePit = runPit(computeCapexToRevenue);
export const computeAndWriteOperatingExpenseRatioPit = runPit(computeOperatingExpenseRatio);
export const computeAndWriteTurnoverRatioFamilyPit = runPit(computeTurnoverRatioFamily);
export const computeAndWriteAssetGrowthPit = runPit(computeAssetGrowth);
export const computeAndWriteBvpsGrowthRatePit = runPit(computeBvpsGrowthRate);
export const computeAndWriteEpsCagrFamilyPit = runPitNested(computeEpsCagrFamily, 'results');
export const computeAndWriteEpsGrowthRatePit = runPit(computeEpsGrowthRate);
export const computeAndWriteEquityGrowthRatePit = runPit(computeEquityGrowthRate);
export const computeAndWriteNetIncomeGrowthRatePit = runPit(computeNetIncomeGrowthRate);
export const computeAndWriteOperatingIncomeGrowthRatePit = runPit(computeOperatingIncomeGrowthRate);
export const computeAndWritePriceToResearchRatioPit = runPit(computePriceToResearchRatio);
export const computeAndWriteRdIntensityPit = runPit(computeRdIntensity);
export const computeAndWriteRevenueCagrFamilyPit = runPitNested(computeRevenueCagrFamily, 'results');
export const computeAndWriteRevenueGrowthRatePit = runPit(computeRevenueGrowthRate);
export const computeAndWriteRuleOf40Pit = runPit(computeRuleOf40);
export const computeAndWriteSgrPit = runPit(computeSgr);
export const computeAndWriteSuePit = runPit(computeSue);
export const computeAndWriteBankIncomeWaterfallPit = runPit(computeBankIncomeWaterfall);
export const computeAndWriteCrociPit = runPit(computeCroci);
export const computeAndWriteEpsPit = runPit(computeEps);
export const computeAndWriteFamaFrenchOperatingProfitabilityPit = runPit(computeFamaFrenchOperatingProfitability);
export const computeAndWriteGreenblattRocPit = runPit(computeGreenblattRoc);
export const computeAndWriteIncomeStatementPerSharePit = runPit(computeIncomeStatementPerShare);
export const computeAndWriteMarginsFamilyPit = runPit(computeMarginsFamily);
export const computeAndWriteNissimPenmanRnoaPit = runPit(computeNissimPenmanRnoa);
export const computeAndWriteNonOperatingIncomeRatioPit = runPit(computeNonOperatingIncomeRatio);
export const computeAndWriteNovyMarxGpToAssetsPit = runPit(computeNovyMarxGpToAssets);
export const computeAndWriteOneDollarTestPit = runPit(computeOneDollarTest);
export const computeAndWritePretaxIncomePerSharePit = runPit(computePretaxIncomePerShare);
export const computeAndWriteRevenuePerSharePit = runPit(computeRevenuePerShare);
export const computeAndWriteRoaPit = runPit(computeRoa);
export const computeAndWriteRocePit = runPit(computeRoce);
export const computeAndWriteRoePit = runPit(computeRoe);
export const computeAndWriteRoicPit = runPit(computeRoic);
export const computeAndWriteAbnormalCapexRatioPit = runPit(computeAbnormalCapexRatio);
export const computeAndWriteAccrualsRatioPit = runPit(computeAccrualsRatio);
export const computeAndWriteBeneishAqiPit = runPit(computeBeneishAqi);
export const computeAndWriteBeneishDsriPit = runPit(computeBeneishDsri);
export const computeAndWriteBeneishMScorePit = runPit(computeBeneishMScore);
export const computeAndWriteCashFlowPerSharePit = runPit(computeCashFlowPerShare);
export const computeAndWriteConsecutiveProfitYearsPit = runPit(computeConsecutiveProfitYears);
export const computeAndWriteFcfMarginPit = runPit(computeFcfMargin);
export const computeAndWriteOcfToNetIncomePit = runPit(computeOcfToNetIncome);
export const computeAndWriteOwnerEarningsPit = runPit(computeOwnerEarnings);
export const computeAndWritePiotroskiFScorePit = runPit(computePiotroskiFScore);
export const computeAndWriteAltmanZDoublePrimeScorePit = runPit(computeAltmanZDoublePrimeScore);
export const computeAndWriteAltmanZScorePit = runPit(computeAltmanZScore);
export const computeAndWriteBankAssetQualityFamilyPit = runPit(computeBankAssetQualityFamily);
export const computeAndWriteBankCapitalAdequacyFamilyPit = runPit(computeBankCapitalAdequacyFamily);
export const computeAndWriteCashToAssetsRatioPit = runPit(computeCashToAssetsRatio);
export const computeAndWriteDebtRatioPit = runPit(computeDebtRatio);
export const computeAndWriteDeRatioPit = runPit(computeDeRatio);
export const computeAndWriteEquityRatioPit = runPit(computeEquityRatio);
export const computeAndWriteInterestCoveragePit = runPit(computeInterestCoverage);
export const computeAndWriteLeverageDegreeFamilyPit = runPit(computeLeverageDegreeFamily);
export const computeAndWriteLiquidityRatioPit = runPit(computeLiquidityRatio);
export const computeAndWriteLongTermDebtToNetCurrentAssetsPit = runPit(computeLongTermDebtToNetCurrentAssets);
export const computeAndWriteNetDebtToEbitdaPit = runPit(computeNetDebtToEbitda);
export const computeAndWriteNetWorkingCapitalToAssetsPit = runPit(computeNetWorkingCapitalToAssets);
export const computeAndWriteOhlsonOScorePit = runPit(computeOhlsonOScore);
export const computeAndWriteTotalDebtToCapitalPit = runPit(computeTotalDebtToCapital);
export const computeAndWriteZmijewskiScorePit = runPit(computeZmijewskiScore);
export const computeAndWriteCashFlowValuationFamilyPit = runPit(computeCashFlowValuationFamily);
export const computeAndWriteDupontFamilyPit = runPit(computeDupontFamily);
export const computeAndWriteMarketRatiosPit = runPit(computeMarketRatios);
export const computeAndWriteBetaPit = runPit(computeBeta);
export const computeAndWriteBvpsPit = runPit(computeBvps);
export const computeAndWriteEarningsYieldPit = runPit(computeEarningsYield);
export const computeAndWriteEvEbitdaPit = runPit(computeEvEbitda);
export const computeAndWriteEvToEbitPit = runPit(computeEvToEbit);
export const computeAndWriteEvToFcfPit = runPit(computeEvToFcf);
export const computeAndWriteFcfYieldPit = runPit(computeFcfYield);
export const computeAndWriteGrahamNumberPit = runPit(computeGrahamNumber);
export const computeAndWriteGreenblattEarningsYieldPit = runPit(computeGreenblattEarningsYield);
export const computeAndWriteLiveGrahamNumberPit = runPit(computeLiveGrahamNumber);
export const computeAndWriteLiveMarketCapPit = runPit(computeLiveMarketCap);
export const computeAndWriteLivePegRatioPit = runPit(computeLivePegRatio);
export const computeAndWriteMarketCapPit = runPit(computeMarketCap);
export const computeAndWriteNcavPit = runPit(computeNcav);
export const computeAndWritePbRatioPit = runPit(computePbRatio);
export const computeAndWritePegRatioPit = runPit(computePegRatio);
export const computeAndWritePeRatioPit = runPit(computePeRatio);
export const computeAndWritePFcfPit = runPit(computePFcf);
export const computeAndWritePsrPit = runPit(computePsr);
export const computeAndWriteStockPricePit = runPit(computeStockPrice);
export const computeAndWriteTobinsQPit = runPit(computeTobinsQ);
